# Generated by Django 5.0.3 on 2024-03-31 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capp', '0002_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('u_address', models.CharField(max_length=255, null=True)),
                ('u_contact', models.IntegerField(null=True)),
                ('u_image', models.ImageField(null=True, upload_to='image/')),
            ],
        ),
    ]
